### PR TITLE
Print the minikube logs after each test run

### PR DESCRIPTION
**Pull request by wallrj**
Hopefully this will give kubelet logs for diagnosing test failures such as https://github.com/jetstack/navigator/pull/168#issuecomment-351103506 where a namespace failed to delete in time....possibly because a container wasn't stopped.

### CODE REVIEW

**Comment by munnerz** [comment]
👍 

Could we adjust this to only print logs on failure? Else we add ~5k extra log lines for each test run even on success is all.

**Comment by wallrj** [comment]
> Could we adjust this to only print logs on failure? Else we add ~5k extra log lines for each test run even on success is all.

I kind of want to see the logs for successes too, so that I can get an idea of what's a normal error and what's an unusual error.

Are you thinking of cost of storage? Or just the distraction of extra logs? If the latter, I find that gubernator does a pretty good job of hiding the boring bits.

**Comment by wallrj** [comment]
@munnerz I've altered it as you suggested (in slack) so that minikube logs are saved to an artifacts directory.
Also took the opportunity to make the logging of commands a bit more consistent and added a measure to prevent minikube doing any interactive bug reporting (which I observe when I test this locally)

Here's the output:

```
KUBERNETES_VERSION=v1.8.4 ./scenarios/minikube.py false
Creating artifacts directory...
Run: 'minikube start --kubernetes-version=v1.8.4 --bootstrapper=kubeadm --memory=4096 --profile=drax'
Starting local Kubernetes v1.8.4 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
Run: 'minikube addons enable ingress --profile=drax'
ingress was successfully enabled
Waiting for kubernetes to become ready...
Run: 'kubectl get nodes'
NAME      STATUS    ROLES     AGE       VERSION
drax      Ready     master    6s        v1.8.4
Run: 'kubectl get nodes'
NAME      STATUS    ROLES     AGE       VERSION
drax      Ready     master    6s        v1.8.4
Run: 'minikube docker-env --profile=drax --shell=sh'
Setting DOCKER_TLS_VERIFY = 1
Setting DOCKER_HOST = tcp://192.168.99.104:2376
Setting DOCKER_CERT_PATH = /home/richard/.minikube/certs
Setting DOCKER_API_VERSION = 1.23
Run: 'docker ps'
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS               NAMES
91c6ddec86d4        7058ac4d4af5                               "kube-controller-m..."   17 seconds ago      Up 17 seconds                           k8s_kube-controller-manager_kube-controller-manager-drax_kube-system_0bcaa96a8b341ce540d28b0c2f049701_0
47fabc8897e1        0d985fed7f95                               "kube-scheduler --..."   17 seconds ago      Up 17 seconds                           k8s_kube-scheduler_kube-scheduler-drax_kube-system_e554495c6f8701f21accd04866090b05_0
8a034b374c2b        243830dae7dd                               "etcd --listen-cli..."   17 seconds ago      Up 17 seconds                           k8s_etcd_etcd-drax_kube-system_baa35922a2db9b50e1760bd4574d15b6_0
03fedd2de464        10a052dccbc5                               "kube-apiserver --..."   18 seconds ago      Up 17 seconds                           k8s_kube-apiserver_kube-apiserver-drax_kube-system_c21fd0a812429056926e613e3dc9ad84_0
5c33c63b6237        0a951668696f                               "/opt/kube-addons.sh"    18 seconds ago      Up 17 seconds                           k8s_kube-addon-manager_kube-addon-manager-drax_kube-system_9831e93c3188555873fdb49f43198eef_0
037130511c5e        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 18 seconds ago      Up 17 seconds                           k8s_POD_kube-scheduler-drax_kube-system_e554495c6f8701f21accd04866090b05_0
12376cb35f48        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 18 seconds ago      Up 17 seconds                           k8s_POD_kube-controller-manager-drax_kube-system_0bcaa96a8b341ce540d28b0c2f049701_0
64e80fc2419f        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 18 seconds ago      Up 17 seconds                           k8s_POD_kube-apiserver-drax_kube-system_c21fd0a812429056926e613e3dc9ad84_0
8cbe624d5d18        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 18 seconds ago      Up 17 seconds                           k8s_POD_kube-addon-manager-drax_kube-system_9831e93c3188555873fdb49f43198eef_0
9302a5223df9        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 18 seconds ago      Up 17 seconds                           k8s_POD_etcd-drax_kube-system_baa35922a2db9b50e1760bd4574d15b6_0
Execute test command
Run: 'false'
Saving minikube logs...
Run: 'minikube --bootstrapper=kubeadm --profile drax logs'
Deleting minikub VM...
Run: 'minikube delete --profile=drax'
Deleting local Kubernetes cluster...
Machine deleted.
Deleting minikube machine files...
Run: 'rm -Rf /var/lib/libvirt/caches/minikube/.minikube/machines/drax'
Traceback (most recent call last):
  File "./scenarios/minikube.py", line 213, in <module>
    main(ARGS.env, ARGS.cmd + ARGS.args)
  File "./scenarios/minikube.py", line 204, in main
    check(*cmd)
  File "./scenarios/minikube.py", line 163, in check
    check_call(cmd)
  File "./scenarios/minikube.py", line 121, in check_call
    kwargs,
  File "./scenarios/minikube.py", line 113, in log_and_closefds_for_subprocess
    return f(cmd, *args, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('false',)' returned non-zero exit status 1

```


And here's the log

```
head _artifacts/minikube-logs.txt 
-- Logs begin at Wed 2017-12-13 12:49:58 UTC, end at Wed 2017-12-13 12:51:45 UTC. --
Dec 13 12:50:41 drax systemd[1]: [/etc/systemd/system/kubelet.service.d/10-kubeadm.conf:7] Unknown lvalue 'Wants' in section 'Install'
Dec 13 12:50:41 drax systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 13 12:50:41 drax kubelet[3299]: Flag --require-kubeconfig has been deprecated, You no longer need to use --require-kubeconfig. This will be removed in a future version. Providing --kubeconfig enables API server mode, omitting --kubeconfig enables standalone mode unless --require-kubeconfig=true is also set. In the latter case, the legacy default kubeconfig path will be used until --require-kubeconfig is removed.
Dec 13 12:50:41 drax kubelet[3299]: I1213 12:50:41.454201    3299 feature_gate.go:156] feature gates: map[]
Dec 13 12:50:41 drax kubelet[3299]: I1213 12:50:41.454321    3299 controller.go:114] kubelet config controller: starting controller
Dec 13 12:50:41 drax kubelet[3299]: I1213 12:50:41.454330    3299 controller.go:118] kubelet config controller: validating combination of defaults and flags
Dec 13 12:50:41 drax kubelet[3299]: I1213 12:50:41.768697    3299 client.go:75] Connecting to docker on unix:///var/run/docker.sock
Dec 13 12:50:41 drax kubelet[3299]: I1213 12:50:41.769173    3299 client.go:95] Start docker client with request timeout=2m0s
Dec 13 12:50:41 drax kubelet[3299]: I1213 12:50:41.823147    3299 feature_gate.go:156] feature gates: map[]
...
Dec 13 12:51:31 drax kubelet[3428]: E1213 12:51:31.858719    3428 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:413: Failed to list *v1.Service: Get https://192.168.99.104:8443/api/v1/services?resourceVersion=0: dial tcp 192.168.99.104:8443: getsockopt: connection refused
Dec 13 12:51:32 drax kubelet[3428]: E1213 12:51:32.059103    3428 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:422: Failed to list *v1.Node: Get https://192.168.99.104:8443/api/v1/nodes?fieldSelector=metadata.name%3Ddrax&resourceVersion=0: dial tcp 192.168.99.104:8443: getsockopt: connection refused
Dec 13 12:51:32 drax kubelet[3428]: E1213 12:51:32.258721    3428 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.99.104:8443/api/v1/pods?fieldSelector=spec.nodeName%3Ddrax&resourceVersion=0: dial tcp 192.168.99.104:8443: getsockopt: connection refused
Dec 13 12:51:32 drax kubelet[3428]: E1213 12:51:32.859860    3428 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:413: Failed to list *v1.Service: Get https://192.168.99.104:8443/api/v1/services?resourceVersion=0: dial tcp 192.168.99.104:8443: getsockopt: connection refused
Dec 13 12:51:34 drax kubelet[3428]: I1213 12:51:34.152324    3428 kubelet_node_status.go:280] Setting node annotation to enable volume controller attach/detach
Dec 13 12:51:34 drax kubelet[3428]: I1213 12:51:34.158687    3428 kubelet_node_status.go:83] Attempting to register node drax
Dec 13 12:51:38 drax kubelet[3428]: I1213 12:51:38.175843    3428 kubelet_node_status.go:86] Successfully registered node drax
Dec 13 12:51:41 drax kubelet[3428]: W1213 12:51:41.578371    3428 conversion.go:110] Could not get instant cpu stats: different number of cpus
Dec 13 12:51:41 drax kubelet[3428]: W1213 12:51:41.582664    3428 helpers.go:847] eviction manager: no observation found for eviction signal allocatableNodeFs.available

```

**Comment by munnerz** [comment]
Great, thanks @wallrj!

**Pull request merged**
