### PR TITLE
Fast forward to test-infra latest

### PR DESCRIPTION
**Pull request by munnerz**
This PR has not yet been deployed to the Prow cluster.

I have had to make a number of changes to the config.yaml file, mostly around properly quoting string-bool values.

/cc @simonswine

### CODE REVIEW

**Comment by munnerz** [comment]
I have also changed tarmak job templates to not include `always_run` and instead opted to include those in the presubmit config itself, to make the job configuration simpler. Take a look at the latest commit to see this change: https://github.com/jetstack/test-infra/pull/214/commits/fb3a65491f8170a19e0ebddf862031f236db9182

**Comment by simonswine** [comment]
This lgtm. We potentially should get the fix for the run_after_success issues in?

/lgtm

**Comment by munnerz** [comment]
Yep I will do that today and hopefully get the tarmak PRs resolved/merged!

**Comment by munnerz** [comment]
I've now rolled this out to production. It took a few extra changes to our config, although nothing major.

Merging.

**Pull request merged**
