### PR TITLE
Migrate to libvirt

### PR DESCRIPTION
**Pull request by simonswine**

### CODE REVIEW

**Comment by munnerz** [comment]
LGTM. Only advice is to namespace the host cache directories by project name (the bundle cache)

**Comment by simonswine** [comment]
@munnerz can I use variables in the YAML? Or just using the makefile?

**Comment by munnerz** [comment]
Which variables do you mean, and in what YAML?

**Comment by simonswine** [comment]
I was not too sure if this works ^^

But it does, not namespacing virtualbox image

**Pull request merged**
